"""数据级联表单

Revision ID: 2c541222abd6
Revises: 4f1012441346
Create Date: 2018-08-02 14:32:26.810076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c541222abd6'
down_revision = '4f1012441346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'isdelete')
    op.add_column('student', sa.Column('s_grade', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'grade', ['s_grade'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 's_grade')
    op.add_column('person', sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
